triggers:
- name: build-and-push
  event: push
  branch: main
  filename: Dockerfile
  build:
    steps:
    - name: 'gcr.io/cloud-builders/docker'
      args: ['build', '-t', 'gcr.io/still-descent-423419-c7/mycalc:gcp', '.']
    - name: 'gcr.io/cloud-builders/docker'
      args: ['login', '-u', '$DOCKERHUB_USERNAME', '-p', '$DOCKERHUB_PASSWORD']
    - name: 'gcr.io/cloud-builders/docker'
      args: ['push', 'valentingarciairiart/mycalc:gcp']
