steps:
# Construir la imagen a partir del Dockerfile en el repositorio
- name: 'Construir_Imagen'
  args: 
    - 'build'
    - '-t'
    - 'gcr.io/$_PROJECT_ID/mycalc:gcp'
    - '.'
  dir: '.'  # Ruta al directorio que contiene el Dockerfile

# Subir la imagen al Artifact Registry
- name: 'Pushear_al_Artifact'
  args: 
    - 'push'
    - 'gcr.io/$_PROJECT_ID/mycalc:gcp'


# Iniciar sesión en Docker Hub
- name: 'Dockerhub_Login'
  args: 
    - 'login'
    - '-u'
    - '$_DOCKERHUB_USERNAME'
    - '-p'
    - '$_DOCKERHUB_PASSWORD'

images:
  - 'valentingarciairiart/mycalc:gcp'
