steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$_PROJECT_ID/mycalc:$COMMIT_SHA', '.']

- name: 'gcr.io/cloud-builders/docker'
  args: ['login', '-u', '$DOCKERHUB_USERNAME', '-p', '$DOCKERHUB_PASSWORD']

- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'valentingarciairiart/mycalc:$COMMIT_SHA']

images:
- 'gcr.io/$_PROJECT_ID/mycalc:$COMMIT_SHA'
