steps:
# Construir la imagen a partir del Dockerfile en el repositorio
- name: 'gcr.io/cloud-builders/docker'
  args: 
    - 'build'
    - '-t'
    - 'gcr.io/$PROJECT_ID/calculadora:gcp'
    - '.'
  dir: '.'  # Ruta al directorio que contiene el Dockerfile
