steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'us-docker.pkg.dev/still-descent-423419-c7/my-project/calc:gcpdeluxe'
      - '.'
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'us-docker.pkg.dev/still-descent-423419-c7/my-project/calc:gcpdeluxe'
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'login'
      - '-u'
      - 'valentingarciairiart'
      - '-p'
      - 'Vale0811!'
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'valentingarciairiart/calc:gcpdeluxe'

images:
  - 'us-docker.pkg.dev/still-descent-423419-c7/my-project/calc:gcpdeluxe'
  - 'valentingarciairiart/calc:gcpdeluxe'
