steps:
# Construir la imagen a partir del Dockerfile en el repositorio
- name: 'gcr.io/cloud-builders/docker'
  args: 
    - 'build'
    - '-t'
    - 'gcr.io/$_PROJECT_ID/mycalc:gcp'
    - '.'
  dir: '.'  # Ruta al directorio que contiene el Dockerfile

# Subir la imagen al Artifact Registry
- name: 'gcr.io/cloud-builders/docker'
  args: 
    - 'push'
    - 'gcr.io/$_PROJECT_ID/mycalc:gcp'

# Iniciar sesión en Docker Hub
- name: 'gcr.io/cloud-builders/docker'
  args: 
    - 'login'
    - '-u'
    - '$_DOCKERHUB_USERNAME'
    - '-p'
    - '$_DOCKERHUB_PASSWORD'

# Empujar la imagen a Docker Hub
- name: 'gcr.io/cloud-builders/docker'
  args: 
    - 'push'
    - 'valentingarciairiart/mycalc:gcp'

images:
  - 'valentingarciairiart/mycalc:gcp'
