steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'us-docker.pkg.dev/still-descent-423419-c7/my-first-project/calc:gcpdeluxe' #necesitas poner la ruta entera al repositorio en el artifact registry
      #la estructura es: ruta original/projectid/nombre del repo en artifact/nombre imagen:tag
      - '.'
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'us-docker.pkg.dev/still-descent-423419-c7/my-first-project/calc:gcpdeluxe'
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'tag'
      # se necesita un paso para tagear por un problema de incompatibilidad si no se tagea
      - 'us-docker.pkg.dev/still-descent-423419-c7/my-first-project/calc:gcpdeluxe'
      - 'valentingarciairiart/calc:gcpdeluxe'      
  - name: 'gcr.io/cloud-builders/docker'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
    secretEnv:
      - 'DOCKER_USERNAME'
      - 'DOCKER_PASSWORD'
  - name: 'gcr.io/cloud-builders/docker' # al estar usando la imagen de docker al poner unicamente esto ya lo pushea
    args:
      - 'push'
      - 'valentingarciairiart/calc:gcpdeluxe'

#es necesario una seccion de imagenes para que las reconozca el cloud build: ahi son 2 imagenes, la del artifact y la de docker (que en realidad es la misma)
images:
  - 'us-docker.pkg.dev/still-descent-423419-c7/my-first-project/calc:gcpdeluxe'
  - 'valentingarciairiart/calc:gcpdeluxe'

#esto es para que cloud build use el secreto dockerhub-credentials creado
availableSecrets:
  - name: 'dockerhub-credentials'
    version: 'latest'
    