steps:
# Construir la imagen a partir del Dockerfile en el repositorio
- name: 'Construir Imagen'
  args: 
    - ['build', '-t', 'gcr.io/$_PROJECT_ID/mycalc:gcp', '.']
  dir: '.'  # Ruta al directorio que contiene el Dockerfile

# Iniciar sesión en Docker Hub
- name: 'Login Dockerhub'
  args: ['login', '-u', '$_DOCKERHUB_USERNAME', '-p', '$_DOCKERHUB_PASSWORD']

# Subir la imagen a Docker Hub
- name: 'Pushear Imagen'
  args: 
    - ['push', 'valentingarciairiart/mycalc:gcp']

images:
  - 'valentingarciairiart/mycalc:gcp'
