steps:
# Construir la imagen a partir del Dockerfile en el repositorio
- name: 'gcr.io/cloud-builders/docker'
  args: 
    - 'build'
    - '-t'
    - 'gcr.io/$PROJECT_ID/mycalc:gcp'
    - '.'
  dir: '.'  # Ruta al directorio que contiene el Dockerfile

# Etiquetar la imagen con la etiqueta de Docker Hub
- name: 'gcr.io/cloud-builders/docker'
  args: 
    - 'tag'
    - 'gcr.io/$PROJECT_ID/mycalc:gcp'
    - 'docker.io/valentingarciairiart/mycalc:gcp'

# Iniciar sesión en Docker Hub
- name: 'gcr.io/cloud-builders/docker'
  args: 
    - 'login'
    - '-u'
    - '$_DOCKERHUB_USERNAME'
    - '-p'
    - '$_DOCKERHUB_PASSWORD'


# Empujar la imagen a Docker Hub
- name: 'gcr.io/cloud-builders/docker'
  args: 
    - 'push'
    - 'docker.io/valentingarciairiart/mycalc:gcp'

images:
  - 'gcr.io/$PROJECT_ID/mycalc:gcp'
  - 'docker.io/valentingarciairiart/mycalc:gcp'