steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'us-docker.pkg.dev/still-descent-423419-c7/my-first-project/calc:gcpdeluxe'
      - '.'
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'us-docker.pkg.dev/still-descent-423419-c7/my-first-project/calc:gcpdeluxe'

images:
  - 'us-docker.pkg.dev/still-descent-423419-c7/my-first-project/calc:gcpdeluxe'